// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "keepshare_user"

// User mapped from table <keepshare_user>
type User struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Email         string    `gorm:"column:email;not null" json:"email"`
	PasswordHash  string    `gorm:"column:password_hash;not null" json:"password_hash"`
	Channel       string    `gorm:"column:channel;not null" json:"channel"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	EmailVerified int32     `gorm:"column:email_verified;not null" json:"email_verified"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
