// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlacklist = "keepshare_blacklist"

// Blacklist mapped from table <keepshare_blacklist>
type Blacklist struct {
	UserID           string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	OriginalLinkHash string    `gorm:"column:original_link_hash;primaryKey" json:"original_link_hash"`
	OriginalLink     string    `gorm:"column:original_link;not null" json:"original_link"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Blacklist's table name
func (*Blacklist) TableName() string {
	return TableNameBlacklist
}
