// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSharedLink = "pikpak_shared_link"

// SharedLink mapped from table <pikpak_shared_link>
type SharedLink struct {
	ShareID      string    `gorm:"column:share_id;primaryKey" json:"share_id"`
	FileID       string    `gorm:"column:file_id;not null" json:"file_id"`
	MasterUserID string    `gorm:"column:master_user_id;not null" json:"master_user_id"`
	WorkerUserID string    `gorm:"column:worker_user_id;not null" json:"worker_user_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName SharedLink's table name
func (*SharedLink) TableName() string {
	return TableNameSharedLink
}
