// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMasterAccount = "pikpak_master_account"

// MasterAccount mapped from table <pikpak_master_account>
type MasterAccount struct {
	UserID          string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	KeepshareUserID string    `gorm:"column:keepshare_user_id;not null" json:"keepshare_user_id"`
	Email           string    `gorm:"column:email;not null" json:"email"`
	Password        string    `gorm:"column:password;not null" json:"password"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MasterAccount's table name
func (*MasterAccount) TableName() string {
	return TableNameMasterAccount
}
