// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFile = "pikpak_file"

// File mapped from table <pikpak_file>
type File struct {
	AutoID           int64     `gorm:"column:auto_id;primaryKey;autoIncrement:true" json:"auto_id"`
	MasterUserID     string    `gorm:"column:master_user_id;not null" json:"master_user_id"`
	WorkerUserID     string    `gorm:"column:worker_user_id;not null" json:"worker_user_id"`
	FileID           string    `gorm:"column:file_id;not null" json:"file_id"`
	TaskID           string    `gorm:"column:task_id;not null" json:"task_id"`
	Status           string    `gorm:"column:status;not null" json:"status"`
	IsDir            bool      `gorm:"column:is_dir;not null" json:"is_dir"`
	Size             int64     `gorm:"column:size;not null" json:"size"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	OriginalLinkHash string    `gorm:"column:original_link_hash;not null" json:"original_link_hash"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
