// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLinkStatus = "pikpak_link_status"

// LinkStatus mapped from table <pikpak_link_status>
type LinkStatus struct {
	AutoID           int64     `gorm:"column:auto_id;primaryKey;autoIncrement:true" json:"auto_id"`
	OriginalLinkHash string    `gorm:"column:original_link_hash;not null" json:"original_link_hash"`
	AccessIPList     string    `gorm:"column:access_ip_list;not null" json:"access_ip_list"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName LinkStatus's table name
func (*LinkStatus) TableName() string {
	return TableNameLinkStatus
}
