// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/KeepShareOrg/keepshare/server/model"
)

func newBlacklist(db *gorm.DB, opts ...gen.DOOption) blacklist {
	_blacklist := blacklist{}

	_blacklist.blacklistDo.UseDB(db, opts...)
	_blacklist.blacklistDo.UseModel(&model.Blacklist{})

	tableName := _blacklist.blacklistDo.TableName()
	_blacklist.ALL = field.NewAsterisk(tableName)
	_blacklist.UserID = field.NewString(tableName, "user_id")
	_blacklist.OriginalLinkHash = field.NewString(tableName, "original_link_hash")
	_blacklist.OriginalLink = field.NewString(tableName, "original_link")
	_blacklist.CreatedAt = field.NewTime(tableName, "created_at")

	_blacklist.fillFieldMap()

	return _blacklist
}

type blacklist struct {
	blacklistDo

	ALL              field.Asterisk
	UserID           field.String
	OriginalLinkHash field.String
	OriginalLink     field.String
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (b blacklist) Table(newTableName string) *blacklist {
	b.blacklistDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blacklist) As(alias string) *blacklist {
	b.blacklistDo.DO = *(b.blacklistDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blacklist) updateTableName(table string) *blacklist {
	b.ALL = field.NewAsterisk(table)
	b.UserID = field.NewString(table, "user_id")
	b.OriginalLinkHash = field.NewString(table, "original_link_hash")
	b.OriginalLink = field.NewString(table, "original_link")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *blacklist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blacklist) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 4)
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["original_link_hash"] = b.OriginalLinkHash
	b.fieldMap["original_link"] = b.OriginalLink
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b blacklist) clone(db *gorm.DB) blacklist {
	b.blacklistDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blacklist) replaceDB(db *gorm.DB) blacklist {
	b.blacklistDo.ReplaceDB(db)
	return b
}

type blacklistDo struct{ gen.DO }

type IBlacklistDo interface {
	gen.SubQuery
	Debug() IBlacklistDo
	WithContext(ctx context.Context) IBlacklistDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBlacklistDo
	WriteDB() IBlacklistDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBlacklistDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBlacklistDo
	Not(conds ...gen.Condition) IBlacklistDo
	Or(conds ...gen.Condition) IBlacklistDo
	Select(conds ...field.Expr) IBlacklistDo
	Where(conds ...gen.Condition) IBlacklistDo
	Order(conds ...field.Expr) IBlacklistDo
	Distinct(cols ...field.Expr) IBlacklistDo
	Omit(cols ...field.Expr) IBlacklistDo
	Join(table schema.Tabler, on ...field.Expr) IBlacklistDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBlacklistDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBlacklistDo
	Group(cols ...field.Expr) IBlacklistDo
	Having(conds ...gen.Condition) IBlacklistDo
	Limit(limit int) IBlacklistDo
	Offset(offset int) IBlacklistDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBlacklistDo
	Unscoped() IBlacklistDo
	Create(values ...*model.Blacklist) error
	CreateInBatches(values []*model.Blacklist, batchSize int) error
	Save(values ...*model.Blacklist) error
	First() (*model.Blacklist, error)
	Take() (*model.Blacklist, error)
	Last() (*model.Blacklist, error)
	Find() ([]*model.Blacklist, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Blacklist, err error)
	FindInBatches(result *[]*model.Blacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Blacklist) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBlacklistDo
	Assign(attrs ...field.AssignExpr) IBlacklistDo
	Joins(fields ...field.RelationField) IBlacklistDo
	Preload(fields ...field.RelationField) IBlacklistDo
	FirstOrInit() (*model.Blacklist, error)
	FirstOrCreate() (*model.Blacklist, error)
	FindByPage(offset int, limit int) (result []*model.Blacklist, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBlacklistDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b blacklistDo) Debug() IBlacklistDo {
	return b.withDO(b.DO.Debug())
}

func (b blacklistDo) WithContext(ctx context.Context) IBlacklistDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blacklistDo) ReadDB() IBlacklistDo {
	return b.Clauses(dbresolver.Read)
}

func (b blacklistDo) WriteDB() IBlacklistDo {
	return b.Clauses(dbresolver.Write)
}

func (b blacklistDo) Session(config *gorm.Session) IBlacklistDo {
	return b.withDO(b.DO.Session(config))
}

func (b blacklistDo) Clauses(conds ...clause.Expression) IBlacklistDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blacklistDo) Returning(value interface{}, columns ...string) IBlacklistDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blacklistDo) Not(conds ...gen.Condition) IBlacklistDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blacklistDo) Or(conds ...gen.Condition) IBlacklistDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blacklistDo) Select(conds ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blacklistDo) Where(conds ...gen.Condition) IBlacklistDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blacklistDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IBlacklistDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b blacklistDo) Order(conds ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blacklistDo) Distinct(cols ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blacklistDo) Omit(cols ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blacklistDo) Join(table schema.Tabler, on ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blacklistDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blacklistDo) RightJoin(table schema.Tabler, on ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blacklistDo) Group(cols ...field.Expr) IBlacklistDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blacklistDo) Having(conds ...gen.Condition) IBlacklistDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blacklistDo) Limit(limit int) IBlacklistDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blacklistDo) Offset(offset int) IBlacklistDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blacklistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBlacklistDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blacklistDo) Unscoped() IBlacklistDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blacklistDo) Create(values ...*model.Blacklist) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blacklistDo) CreateInBatches(values []*model.Blacklist, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blacklistDo) Save(values ...*model.Blacklist) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blacklistDo) First() (*model.Blacklist, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Take() (*model.Blacklist, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Last() (*model.Blacklist, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Find() ([]*model.Blacklist, error) {
	result, err := b.DO.Find()
	return result.([]*model.Blacklist), err
}

func (b blacklistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Blacklist, err error) {
	buf := make([]*model.Blacklist, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blacklistDo) FindInBatches(result *[]*model.Blacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blacklistDo) Attrs(attrs ...field.AssignExpr) IBlacklistDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blacklistDo) Assign(attrs ...field.AssignExpr) IBlacklistDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blacklistDo) Joins(fields ...field.RelationField) IBlacklistDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blacklistDo) Preload(fields ...field.RelationField) IBlacklistDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blacklistDo) FirstOrInit() (*model.Blacklist, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) FirstOrCreate() (*model.Blacklist, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) FindByPage(offset int, limit int) (result []*model.Blacklist, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blacklistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blacklistDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blacklistDo) Delete(models ...*model.Blacklist) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blacklistDo) withDO(do gen.Dao) *blacklistDo {
	b.DO = *do.(*gen.DO)
	return b
}
